[odps]
access_key_id = "LTAI5tEHcsAw6c9P3TqwtiMd"
access_key_secret = "AzM3KGo4oMcjqWYt3llArBUw7ZC90P"
project = "yswy_ads"
endpoint = "http://service.cn-hangzhou.maxcompute.aliyun.com/api"

[openai]
api_key = "sk-kzgaqntobekqayahwsffjmkncwmjeplbwvwrsazozwvzutcr"
base_url = "https://api.siliconflow.cn/v1"
model = "Qwen/Qwen3-30B-A3B"

[tushare]
token = "8bd3ad65a82d609215b8a5ac92553993e0301b7e83da3abe223742bc"

[mysql]
host = "yjdf-uat.rwlb.rds.aliyuncs.com"
user = "woouo"
password = "t9e5OKmUBpJwLu8l"
database = "yswy_zy"